[tool.poetry]
name = "forecasting-with-machine-learning"
version = "0.1.0"
description = ""
authors = ["Nuno Svensson <nuosvensson@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.10.0"
pandas = "^2.2.3"
feature-engine = "^1.8.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[virtualenvs]
in-project = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
